-- MySQL Script generated by MySQL Workbench
-- Sun Mar 10 11:56:21 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`d_cliente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`d_cliente` (
  `id_cliente` INT NOT NULL,
  `nombres` VARCHAR(45) NULL,
  `tipo_doc` VARCHAR(45) NULL,
  `num_doc` VARCHAR(45) NULL,
  `fec_nac` VARCHAR(45) NULL,
  `tlf_movil` VARCHAR(45) NULL,
  `tlf_fijo` VARCHAR(45) NULL,
  `mail` VARCHAR(45) NULL,
  `segmento` VARCHAR(45) NULL,
  PRIMARY KEY (`id_cliente`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`t_tienda`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`t_tienda` (
  `idt_tienda` INT NOT NULL,
  `direccion` VARCHAR(45) NULL,
  `distrito` VARCHAR(45) NULL,
  `provincia` VARCHAR(45) NULL,
  `departamento` VARCHAR(45) NULL,
  PRIMARY KEY (`idt_tienda`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`d_categoriaProd`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`d_categoriaProd` (
  `id_catprod` INT NOT NULL,
  `dscp` VARCHAR(45) NULL,
  PRIMARY KEY (`id_catprod`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`d_subCategoriaProd`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`d_subCategoriaProd` (
  `id_subcatprod` INT NOT NULL,
  `id_catprod` INT NOT NULL,
  `dscp` VARCHAR(45) NULL,
  PRIMARY KEY (`id_subcatprod`),
  INDEX `fk_d_subCategoriaProd_d_categoriaProd1_idx` (`id_catprod` ASC),
  CONSTRAINT `fk_d_subCategoriaProd_d_categoriaProd1`
    FOREIGN KEY (`id_catprod`)
    REFERENCES `mydb`.`d_categoriaProd` (`id_catprod`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`d_producto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`d_producto` (
  `id_producto` INT NOT NULL,
  `id_subcatprod` INT NOT NULL,
  `unidad` VARCHAR(45) NULL,
  `nombre` VARCHAR(45) NULL,
  `marca` VARCHAR(45) NULL,
  `stock` VARCHAR(45) NULL,
  `proveedor` VARCHAR(45) NULL,
  `precio_compra` VARCHAR(45) NULL,
  `precio_vta` VARCHAR(45) NULL,
  `igv` VARCHAR(45) NULL,
  `dcto` VARCHAR(45) NULL,
  PRIMARY KEY (`id_producto`),
  INDEX `fk_d_producto_d_subCategoriaProd1_idx` (`id_subcatprod` ASC),
  CONSTRAINT `fk_d_producto_d_subCategoriaProd1`
    FOREIGN KEY (`id_subcatprod`)
    REFERENCES `mydb`.`d_subCategoriaProd` (`id_subcatprod`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`d_tiempo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`d_tiempo` (
  `id_tiempo` INT NOT NULL,
  `fecha` VARCHAR(45) NULL,
  `anio` VARCHAR(45) NULL,
  `trimestre` VARCHAR(45) NULL,
  `mes` VARCHAR(45) NULL,
  `semana` VARCHAR(45) NULL,
  `dia` VARCHAR(45) NULL,
  `hora` VARCHAR(45) NULL,
  PRIMARY KEY (`id_tiempo`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`fact_table`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`fact_table` (
  `id_factura` INT NOT NULL,
  `d_cliente_id_cliente` INT NOT NULL,
  `t_tienda_idt_tienda` INT NOT NULL,
  `d_producto_id_producto` INT NOT NULL,
  `d_tiempo_id_tiempo` INT NOT NULL,
  `monto_vta` DECIMAL(15) NULL,
  `unidad_prod` INT NOT NULL,
  `id_empleado` VARCHAR(45) NULL,
  PRIMARY KEY (`id_factura`),
  INDEX `fk_fact_table_d_cliente_idx` (`d_cliente_id_cliente` ASC),
  INDEX `fk_fact_table_t_tienda1_idx` (`t_tienda_idt_tienda` ASC),
  INDEX `fk_fact_table_d_producto1_idx` (`d_producto_id_producto` ASC),
  INDEX `fk_fact_table_d_tiempo1_idx` (`d_tiempo_id_tiempo` ASC),
  CONSTRAINT `fk_fact_table_d_cliente`
    FOREIGN KEY (`d_cliente_id_cliente`)
    REFERENCES `mydb`.`d_cliente` (`id_cliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_fact_table_t_tienda1`
    FOREIGN KEY (`t_tienda_idt_tienda`)
    REFERENCES `mydb`.`t_tienda` (`idt_tienda`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_fact_table_d_producto1`
    FOREIGN KEY (`d_producto_id_producto`)
    REFERENCES `mydb`.`d_producto` (`id_producto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_fact_table_d_tiempo1`
    FOREIGN KEY (`d_tiempo_id_tiempo`)
    REFERENCES `mydb`.`d_tiempo` (`id_tiempo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
